r"""qnm-package cross-check for the Kerr QNM baseline.

This script uses Leo Stein's `qnm` package to compute Kerr QNM frequencies
from the cached spin sequences, then compares them with the Berti-Cardoso-Will
fitting formulas generated by the Wolfram script.

Run:
    C:\Users\vrb0015\.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe scripts/python/qnm_solver_crosscheck.py

The package itself is installed locally under `.deps/python`; the precomputed
spin-sequence cache lives under the user's `.qnm` directory.
"""

from __future__ import annotations

import csv
import math
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / ".deps" / "python"))

import qnm  # noqa: E402


SOLAR_MASS_TIME_SECONDS = 4.925490947e-6
MASS_DETECTOR_MSUN = 68.1
SPIN = 0.68

MODES = {
    "220": {"s": -2, "l": 2, "m": 2, "n": 0},
    "221": {"s": -2, "l": 2, "m": 2, "n": 1},
    "222": {"s": -2, "l": 2, "m": 2, "n": 2},
    "330": {"s": -2, "l": 3, "m": 3, "n": 0},
    "440": {"s": -2, "l": 4, "m": 4, "n": 0},
}


def read_berti_csv(path: Path) -> dict[str, dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return {row["mode"]: row for row in csv.DictReader(handle)}


def qnm_row(mode: str) -> dict[str, float | str]:
    seq = qnm.modes_cache(**MODES[mode])
    omega, _angular_constant, _mixing = seq(a=SPIN)
    m_seconds = MASS_DETECTOR_MSUN * SOLAR_MASS_TIME_SECONDS
    momega_real = float(omega.real)
    momega_imag = float(omega.imag)
    f_hz = momega_real / (2.0 * math.pi * m_seconds)
    tau_ms = 1000.0 * m_seconds / abs(momega_imag)
    quality = momega_real / (2.0 * abs(momega_imag))
    return {
        "mode": mode,
        "mass_detector_msun": MASS_DETECTOR_MSUN,
        "spin": SPIN,
        "qnm_Momega_real": momega_real,
        "qnm_Momega_imag": momega_imag,
        "qnm_f_Hz": f_hz,
        "qnm_Q": quality,
        "qnm_tau_ms": tau_ms,
    }


def pct_difference(new: float, baseline: float) -> float:
    return 100.0 * (new - baseline) / baseline


def main() -> None:
    result_dir = ROOT / "results" / "gw250114_kerr_qnm"
    berti_csv = result_dir / "gw250114_kerr_qnm_berti.csv"
    out_csv = result_dir / "qnm_solver_crosscheck.csv"
    out_report = result_dir / "qnm_solver_crosscheck_report.md"

    berti_rows = read_berti_csv(berti_csv)
    rows: list[dict[str, float | str]] = []
    for mode in MODES:
        qrow = qnm_row(mode)
        brow = berti_rows[mode]
        qrow.update(
            {
                "berti_Momega": float(brow["Momega"]),
                "berti_f_Hz": float(brow["f_Hz"]),
                "berti_Q": float(brow["Q"]),
                "berti_tau_ms": float(brow["tau_ms"]),
                "delta_f_pct": pct_difference(float(qrow["qnm_f_Hz"]), float(brow["f_Hz"])),
                "delta_tau_pct": pct_difference(float(qrow["qnm_tau_ms"]), float(brow["tau_ms"])),
            }
        )
        rows.append(qrow)

    fields = [
        "mode",
        "mass_detector_msun",
        "spin",
        "qnm_Momega_real",
        "qnm_Momega_imag",
        "qnm_f_Hz",
        "qnm_Q",
        "qnm_tau_ms",
        "berti_Momega",
        "berti_f_Hz",
        "berti_Q",
        "berti_tau_ms",
        "delta_f_pct",
        "delta_tau_pct",
    ]
    with out_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    report_lines = [
        "# qnm Solver Cross-Check",
        "",
        "This report compares the exact cached Kerr sequences from the Python `qnm` package with the Berti-Cardoso-Will fitting formulas used by the Wolfram baseline.",
        "",
        "Inputs:",
        "",
        f"- `M_f,det = {MASS_DETECTOR_MSUN} Msun`",
        f"- `a = {SPIN}`",
        "- `qnm` cache: downloaded precomputed data under the user `.qnm` directory",
        "",
        "| mode | qnm f [Hz] | Berti f [Hz] | delta f [%] | qnm tau [ms] | Berti tau [ms] | delta tau [%] |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        report_lines.append(
            "| {mode} | {qnm_f_Hz:.6f} | {berti_f_Hz:.6f} | {delta_f_pct:.3f} | {qnm_tau_ms:.6f} | {berti_tau_ms:.6f} | {delta_tau_pct:.3f} |".format(
                **row
            )
        )
    report_lines.extend(
        [
            "",
            "Interpretation:",
            "",
            "- Reproduction: the Wolfram values use published Berti fitting formulas.",
            "- Numerical control: `qnm` evaluates cached Kerr spin sequences and gives an independent Kerr-spectrum check.",
            "- The two methods are not expected to agree exactly; the fitting formulas are approximations to the numerical Kerr spectrum.",
            "",
        ]
    )
    out_report.write_text("\n".join(report_lines), encoding="utf-8")

    print(f"qnm solver cross-check written to: {out_csv}")
    print(f"Report written to: {out_report}")
    for row in rows:
        print(
            "{mode}: qnm f={qnm_f_Hz:.6f} Hz, Berti f={berti_f_Hz:.6f} Hz, delta={delta_f_pct:.3f}%".format(
                **row
            )
        )


if __name__ == "__main__":
    main()
